// angular/l-shoppingapp/src/app/components/navbar.component.ts
import {Component} from '@angular/core';
import {LoginService} from '../services/loginservice.service';
import {Router} from '@angular/router';

@Component({
	selector:"navbar",
	templateUrl:"./navbar.component.html"
})
export class Navbar {
	
	constructor(private login:LoginService,private router:Router) {}
	
	isUserLogged() {
		return this.login.isUserLogged()
	}
	
	logout() {
		this.login.logout().subscribe({
			next: (data) => console.log(data),
			error: (error) => {
				this.login.setLoginState(false,"");
				this.router.navigate(["/"])
			},
			complete: () => {
				this.login.setLoginState(false,"");
				this.router.navigate(["/"])
			}
		})
	}
}
<nav class="navbar navbar-extend-lg navbar-light bg-light">
	<p class="navbar-brand">Shopping App</p>
	<ul class="navbar-nav" *ngIf="isUserLogged(); else notLogged">
		<li class="nav-item">
			<a class="nav-link" routerLink="/list">Shopping List</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" routerLink="/form">Add new item</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" routerLink="/" (click)="logout()">Logout</a>
		</li>
	</ul>	
	<ng-template #notLogged>
		<ul class="navbar-nav"></ul>
	</ng-template>
</nav>

// react/50_shopping_app/06_stage_passportjs/frontend/src/components/Navbar.js
import {Link} from 'react-router-dom';
import useAction from '../hooks/useAction';
import useAppState from '../hooks/useAppState';

const Navbar = (props) => {
	
	const {isLogged,user} = useAppState();
	const {logout} = useAction();
	
	if(isLogged) {
		return(
			<nav className="navbar navbar-expand-lg navbar-light bg-light">
				<p className="navbar-brand" style={{marginLeft:10}}>Shopping App</p>
				<ul className="navbar-nav">
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/" className="nav-link">Shopping List</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/form" className="nav-link">Add new item</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/"  onClick={logout} className="nav-link">Logout</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<p className="nav-link" style={{color:"blue"}}>Logged in as {user}</p>
					</li>
				</ul>
			</nav>
		)
	} else {
		return(
			<nav className="navbar navbar-expand-lg navbar-light bg-light">
				<p className="navbar-brand" style={{marginLeft:10}}>Shopping App</p>
			</nav>
		)
	}
}

export default Navbar;
