// react/06_lists/src/components/ContactForm.js
import {useState} from 'react';

const ContactForm = (props) => {

	const [state,setState] = useState({
		firstname:"",
		lastname:"",
		email:"",
		phone:""
	})
	
	const onChange = (event) => {
		setState((state) => {
			return {
				...state,
				[event.target.name]:event.target.value
			}
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		let contact = {
			...state
		}
		props.addContact(contact);
		setState({
			firstname:"",
			lastname:"",
			email:"",
			phone:""
		})
	}
	return(
		<div style={{
			backgroundColor:"lightgreen",
			width:"40%",
			margin:"auto"
		}}>
			<form onSubmit={onSubmit}>
				<label htmlFor="firstname">First Name</label>
				<input type="text"
						name="firstname"
						id="firstname"
						onChange={onChange}
						value={state.firstname}/>
				<br/>
				<label htmlFor="lastname">Last Name</label>
				<input type="text"
						name="lastname"
						id="lastname"
						onChange={onChange}
						value={state.lastname}/>
				<br/>				
				<label htmlFor="email">Email</label>
				<input type="email"
						name="email"
						id="email"
						onChange={onChange}
						value={state.email}/>
				<br/>
				<label htmlFor="phone">Phone</label>
				<input type="tel"
						name="phone"
						id="phone"
						onChange={onChange}
						value={state.phone}/>
				<br/>
				<input type="submit" value="Add"/>
			</form>
		</div>
	
	)
}

export default ContactForm;

// angular/i-routing_one/src/app/components/contactform.component.ts
import {Component} from '@angular/core'
import {Contact} from '../models/contact.model';
import {ContactService} from '../services/contactservice.service';

@Component({
	selector:"contact-form",
	templateUrl:"./contactform.component.html"
})
export class ContactForm {
	
	contact:Contact = new Contact("","","","",0);
	
	constructor(private contactService:ContactService) {}
	
	addContact() {
		this.contactService.addContact(this.contact);
		this.contact = new Contact("","","","",0);
	}	
}
<form (ngSubmit)="addContact()" #contactForm="ngForm">
	<label for="firstname">First Name</label>
	<input type="text"
			name="firstname"
			id="firstname"
			[(ngModel)]="contact.firstname"/>
	<br/>
	<label for="lastname">Last Name</label>
	<input type="text"
			name="lastname"
			id="lastname"
			[(ngModel)]="contact.lastname"/>
	<br/>
	<label for="email">Email</label>
	<input type="email"
			name="email"
			id="email"
			[(ngModel)]="contact.email"/>
	<br/>
	<label for="phone">Phone</label>
	<input type="tel"
			name="phone"
			id="phone"
			[(ngModel)]="contact.phone"/>
	<br/>
	<input type="submit" value="Add Contact"/>
</form>
